### PR TITLE
TASK: Add DistributionPackages folder

### PR DESCRIPTION
**Pull request by echavaillaz**
This pull request fix the error The url supplied for the path (./DistributionPackages/*) repository does not exist when trying to create a project with the composer command: composer create-project --keep-vcs neos/flow-base-distribution Quickstart.

Thanks

### CODE REVIEW

**Review by albe — APPROVED** [review]

**Comment by albe** [comment]
Thanks a lot!

**Comment by niko5** [comment]
I still seem to be getting the error - not quite sure why using php 7.2.24

**Comment by echavaillaz** [comment]
Not tagged, so It is normal

**Comment by niko5** [comment]
so no good with composer then ?

**Comment by albe** [comment]
Yeah, I need to get around tagging a new release. I'll hopefully do it later today

**Comment by albe** [comment]
FYI: Tagged releases just now - please LMK if anything still not okay with that

**Pull request merged**
